# Configuraci칩n de Netlify para un proyecto con frontend en React/Vite y backend en Node.js/Express

[build]
  # Comando para construir el proyecto frontend
  command = "npm run build"
  
  # Directorio donde se encuentran los archivos construidos
  publish = "front/dist"

# Configuraci칩n de funciones (si est치s usando funciones de Netlify)
[functions]
  # Directorio donde est치n las funciones de Netlify
  directory = "backend/functions"

# Reglas de redireccionamiento y reescritura
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true